name: Deploy WordPress

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Package repo
        run: |
          git archive --format=tar.gz -o app_$(date +"%Y-%m-%d").tar.gz HEAD
          # mv app_$(date +%Y-%m-%d).tar.gz ${{ secrets.S3_BUCKET }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to autoscaling group
        run: |
          mv app_$(date +%Y-%m-%d).tar.gz ${{ secrets.S3_BUCKET }}
          aws s3 cp ${{ secrets.S3_BUCKET }}/app_$(date +%Y-%m-%d).tar.gz s3://{{ secrets.S3_BUCKET }}/
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name lu --min-size 1 --max-size 2
      
      - name: Set S3 bucket expiry policy
        run: |
          aws s3api put-bucket-lifecycle-configuration --bucket ${{ secrets.S3_BUCKET }} --lifecycle-configuration '{
            "Rules": [
              {
                "Expiration": {
                  "Days": 7
                },
                "Status": "Enabled"
              }
            ]
          }'
